version: '3'

volumes:
  db-data:
    external: false

services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/db-data
    ports:
      - "5432:5432"
  
  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
      - "15672:15672"
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: ./Scripts/run_django.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./Scripts/run_celery.sh
    volumes: 
      - .:/usr/src/app
    links:
      - rabbit
      - db
    depends_on:
      - rabbit
      - beat
      - db
      - app
  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./Scripts/run_beat.sh
    volumes:
      - .:/usr/src/app
    links:
      - rabbit
      - db
    depends_on:
      - rabbit
      - db
      - app

